bind(
  name = "libssl",
  actual = "//third_party/boringssl:ssl",
)

bind(
  name = "zlib",
  actual = "//third_party/zlib",
)

# Protobuf compiler binary
bind(
  name = "protoc",
  actual = "//third_party/protobuf/upstream:protoc"
)

# Library needed to build protobuf codegen plugin.
bind(
  name = "protobuf_compiler",
  actual = "//third_party/protobuf/upstream:protoc_lib",
)

# Library that C++ code generated by protobuf C compiler should depend
# on.
bind(
  name = "protobuf_clib",
  actual = "//third_party/protobuf/upstream:protobuf",
)

bind(
  name = "protobuf_java_lib",
  actual = "//third_party/protobuf/upstream:java_proto",
)

# GRPC codegen plugin
bind(
  name = "grpc_cpp_plugin",
  actual = "//third_party/grpc/upstream:grpc_cpp_plugin"
)

# GRPC C++ runtime library
bind(
  name = "grpc++",
  actual = "//third_party/grpc/upstream:grpc++"
)

# gflags
bind(
  name = "gflags",
  actual = "//third_party/gflags"
)

# Disable loading of any android depenedency rule
bind(name = "android/aar_generator")
bind(name = "android/incremental_split_stub_application")
bind(name = "android/incremental_stub_application")
bind(name = "android/resources_processor")
